package org.sean.blackjack.domain;

import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

@Entity (name="mycardtable")
public class Card  {

	@Id
	@GeneratedValue
	private int cardId;
	@Enumerated(EnumType.STRING)
	private Suit suit;
	@Enumerated(EnumType.STRING)
	private Rank rank;
	
	
	//I need to investigate if I need a setCardId and if I actually need a getCrdId for Hibernate
	//cardId is auto-generated by Hibernate when cards are persisted.
	//CAn I do any unit testing of the cardId methods?
	public int getCardId() {
		return cardId;
	}

	public Rank getRank() {
		return rank;
	}
	public void setRank(Rank rank) {
		this.rank = rank;
	}
	public Suit getSuit() {
		return suit;
	}
	public void setSuit(Suit suit) {
		this.suit = suit;
	}
	
	public Card() {
		super();
	}
	
	//Note that the Card constructor does not include cardId.
	//That is because cardId is auto-generated by Hibernate when cards are persisted. 
	public Card(Suit suit, Rank rank) {
		super();
		this.rank = rank;
		this.suit = suit;
	}


}


